<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    function search($word)
    {
        $query = $this->createQueryBuilder('u');

        return $query->where($query->expr()->like('u.name', ':name'))
            ->setParameter('name', '%'.$word.'%')
            ->getQuery()->getResult();
    }
}
